os: linux
language: c
compiler: gcc
before_install:
  - git clone --depth=1 https://github.com/radare/radare2
  - cd radare2 && sys/install.sh && cd ..
  - r2pm init
  - r2pm -i vala
  - r2pm -i valabind
script:
  - cd python
  - r2pm -r make -j2
